# Basic Supervised Linear Models

## Import Pacakges

In [10]:
import tensorflow as tf
import torch

import numpy as np
import sys

from d2l import tensorflow as d2l_tf
from d2l import torch as d2l_torch

## Problem - Regression

### Data Preparation

In [11]:
true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l_tf.synthetic_data(true_w, true_b, 1000)

In [12]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

In [13]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [14]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 0.38556144,  0.46798027],
        [-1.0822797 , -1.5813764 ],
        [ 1.8695663 ,  0.97798365],
        [-0.536385  ,  2.6069794 ],
        [ 1.3276417 ,  0.53860104],
        [ 1.5891473 , -0.47093946],
        [-2.4650126 , -0.65770197],
        [-0.11323174, -0.7895348 ],
        [ 1.1749082 , -0.7547458 ],
        [ 0.51316386,  1.404241  ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 3.3851452 ],
        [ 7.4212036 ],
        [ 4.609002  ],
        [-5.7508397 ],
        [ 5.0231094 ],
        [ 8.974861  ],
        [ 1.5128747 ],
        [ 6.6552925 ],
        [ 9.130929  ],
        [ 0.46831405]], dtype=float32)>)

---

### Model Training

#### TF Sequential API

In [15]:
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

#### TF Functional API